version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: node:20
    container_name: nestjs_backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    command: tail -f /dev/null # Keeps the container running for manual initialization
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: node:20
    container_name: angular_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4200:4200"
    command: tail -f /dev/null # Keeps the container running for manual initialization
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
